/*
 * AnyPay
 *
 * This the AnyPay service targeted towards, parents with children doing payments and russian oligarks
 *
 * API version: 1.0.0
 * Contact: per.von.rosen@swedbank.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"bytes"
	"net/http"
	"testing"

	openapi "github.com/pvr1/anypay/go"
	"github.com/stretchr/testify/assert"
)

func TestAddAccount(t *testing.T) {
	/*
		body := gin.H{
			"Username":            "Kalle",
			"FirstName":           "Carl",
			"LastName":            "Karlsson",
			"Email":               "carl@Karlsson.se",
			"SocialSecuityNumber": "7001016939",
			"Phone":               "+462120000",
		}
	*/

	body := bytes.NewBufferString("Username=Kalle&FirstName=Carl&LastName=Piper&Email=carl@piper.se&SocialSecuityNumber=7001016939&Phone=+462120000")

	router := openapi.NewRouter()
	w := performRequest(router, "POST", "/anypay/v1/accounts", body)
	assert.Equal(t, http.StatusOK, w.Code)

	/*
		var response map[string]string
		err := json.Unmarshal([]byte(w.Body.String()), &response)
		value, exists := response["hello"]
		assert.Nil(t, err)
		assert.True(t, exists)
		assert.Equal(t, "hello", value)
	*/

	a := w.Body.String()
	assert.Equal(t, "Account added\n", a)
}

func TestGetAccount(t *testing.T) {
	/*
		body := gin.H{
			"userID": "1",
		}
	*/

	body := bytes.NewBufferString("userID=1")
	router := openapi.NewRouter()
	w := performRequest(router, "GET", "/anypay/v1/accounts/1", body)
	assert.Equal(t, http.StatusOK, w.Code)

	/*
		var response map[string]string
		err := json.Unmarshal([]byte(w.Body.String()), &response)
		value, exists := response["hello"]
		assert.Nil(t, err)
		assert.True(t, exists)
		assert.Equal(t, body["hello"], value)
	*/

	a := w.Body.String()
	assert.Equal(t, "There you got your specific Account\n", a)
}

func TestGetAccounts(t *testing.T) {
	/*
		body := gin.H{
			"": "",
		}
	*/
	router := openapi.NewRouter()
	w := performRequest(router, "GET", "/anypay/v1/accounts", nil)
	assert.Equal(t, http.StatusOK, w.Code)

	a := w.Body.String()
	assert.Equal(t, "Yep. A list of accounts was delivered. Can you see it?? :-)\n", a)
}

func TestUpdateAccount(t *testing.T) {
	body := bytes.NewBufferString("userID=1")
	router := openapi.NewRouter()
	w := performRequest(router, "PUT", "/anypay/v1/accounts", body)
	assert.Equal(t, http.StatusOK, w.Code)

	/*
		var response map[string]stringThere you got your specific transaction
		err := json.Unmarshal([]byte(w.Body.String()), &response)
		value, exists := response["hello"]
		assert.Nil(t, err)
		assert.True(t, exists)
		assert.Equal(t, body["hello"], value)
	*/

	a := w.Body.String()
	assert.Equal(t, "Account updated. Now it belongs to me.\n", a)
}
