/*
 * AnyPay
 *
 * This the AnyPay service targeted towards, parents with children doing payments and russian oligarks
 *
 * API version: 1.0.0
 * Contact: pr.von.rosen@swedbank.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Transaction struct {

	TransactionId string `json:"transactionId,omitempty"`

	Name string `json:"name,omitempty"`

	Purpose string `json:"purpose,omitempty"`

	Account *Account `json:"account,omitempty"`

	Value *float64 `json:"value,omitempty"`

	Currency string `json:"currency,omitempty"`
}
