/*
 * AnyPay
 *
 * This the AnyPay service targeted towards, parents with children doing payments and russian oligarks
 *
 * API version: 1.0.0
 * Contact: pr.von.rosen@swedbank.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Fxorder struct {

	Id int64 `json:"id,omitempty"`

	FX int64 `json:"FX,omitempty"`

	Account *Account `json:"account,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	OrderDate time.Time `json:"orderDate,omitempty"`

	SettlementDate time.Time `json:"settlementDate,omitempty"`
	// Order Status
	Status string `json:"status,omitempty"`

	Complete bool `json:"complete,omitempty"`
}
