/*
 * AnyPay
 *
 * This the AnyPay service targeted towards, parents with children doing payments and russian oligarks
 *
 * API version: 1.0.0
 * Contact: pr.von.rosen@swedbank.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Payment struct {

	PaymentId string `json:"paymentId,omitempty"`

	Name string `json:"name"`

	Purpose string `json:"purpose,omitempty"`

	FromAccountId int32 `json:"fromAccountId"`

	ToAccountId int32 `json:"toAccountId"`

	Value *float64 `json:"value"`

	Currency string `json:"currency"`
}
