/*Package swagger AnyPay
 *
 * AnyPay
 *
 * This the AnyPay service targeted towards, parents with children doing payments and russian oligarks
 *
 * API version: 1.0.0
 * Contact: pr.von.rosen@swedbank.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

/*Account - a struct holding the account data necessary to IDentify and use and account*/
type Account struct {
	AccountID string `json:"accountID,omitempty"`

	User *User `json:"user,omitempty"`

	Name string `json:"name"`

	Purpose string `json:"purpose,omitempty"`

	AccountType string `json:"accountType"`
}
