/*
 * AnyPay
 *
 * This the AnyPay service targeted towards, parents with children doing payments and russian oligarks
 *
 * API version: 1.0.0
 * Contact: per.von.rosen@swedbank.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

/*Transaction - a struct holding the Transaction data necessary to IDentify and return a Transaction
 *A Transaction is created after an Order has been executed. Order can be of type FX Order or Payment
 */
type Transaction struct {
	TransactionID string `json:"transactionID,omitempty"`

	Name string `json:"name,omitempty"`

	Purpose string `json:"purpose,omitempty"`

	Account Account `json:"account,omitempty"`

	Value float32 `json:"value,omitempty"`

	Currency string `json:"currency,omitempty"`
}
